### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by liyujiang-gzu** [JeremyLiao/LiveDataBus#10]
加油，看好谷歌官方的【 Lifecycle +LiveData + ViewModel +Room】的架构组件

**Comment by JeremyLiao** [comment]
谢谢，同看好：）

**Comment by liyujiang-gzu** [comment]
今天刚刚更新Android Studio 3.2，直接内置支持Activity+Fragment+ViewModel的新建了

**Comment by JeremyLiao** [comment]
嗯，Google官方会大力推行这套框架

**Comment by ShowMeThe** [comment]
作为新人，最近在尝试在公司Android组推荐这个Lifecycle +LiveData + ViewModel的使用 的确是很好用
